-- Filtered SendGrid events: open/click only, mc_auto_name non-blank (via sendgrid-webhook-autoname Edge Function).

CREATE TABLE IF NOT EXISTS public.sendgrid_events_autoname (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  entry_date date NOT NULL DEFAULT CURRENT_DATE,

  email text,
  event text,
  mc_auto_name text,
  mc_auto_unique_id text,
  asm_group_id text,
  ip text,
  mc_auto_id text,
  mc_auto_msg_id text,
  mc_auto_step_id text,
  mc_pod_id text,
  mc_stats text,
  sg_event_id text,
  sg_message_id text,
  sg_template_id text,
  template_hash text,
  template_id text,
  template_version_id text,
  event_timestamp bigint,
  url text,

  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE public.sendgrid_events_autoname IS
  'SendGrid open/click events with non-empty mc_auto_name only. Populated by sendgrid-webhook-autoname Edge Function.';

CREATE INDEX IF NOT EXISTS sendgrid_events_autoname_created_at_idx ON public.sendgrid_events_autoname (created_at DESC);
CREATE INDEX IF NOT EXISTS sendgrid_events_autoname_entry_date_idx ON public.sendgrid_events_autoname (entry_date);
CREATE INDEX IF NOT EXISTS sendgrid_events_autoname_event_idx ON public.sendgrid_events_autoname (event);
CREATE INDEX IF NOT EXISTS sendgrid_events_autoname_mc_auto_name_idx ON public.sendgrid_events_autoname (mc_auto_name);

ALTER TABLE public.sendgrid_events_autoname ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sendgrid_events_autoname_authenticated_select ON public.sendgrid_events_autoname;
CREATE POLICY sendgrid_events_autoname_authenticated_select
ON public.sendgrid_events_autoname
FOR SELECT
TO authenticated
USING (true);

GRANT SELECT ON public.sendgrid_events_autoname TO authenticated;
GRANT SELECT, INSERT ON public.sendgrid_events_autoname TO service_role;
