-- Table: soldoutvins
-- Mirrors MySQL phpMyAdmin structure (varchar(255) text fields, sold/pull dates, pull_date_time).
-- MySQL bigint AUTO_INCREMENT -> bigint GENERATED BY DEFAULT AS IDENTITY
-- MySQL datetime(6) -> timestamptz(6) (aligned with normalized_inventory_from_scrap)

CREATE TABLE IF NOT EXISTS public.soldoutvins (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id        bigint,
  sold_date          date,
  pull_date          date,
  "condition"        varchar(255),
  year               varchar(255),
  make               varchar(255),
  model              varchar(255),
  vin                varchar(255),
  advertiser         varchar(255),
  formatted_price    varchar(255),
  location           varchar(255),
  price              varchar(255),
  title              varchar(255),
  custom_type        varchar(255),
  custom_make        varchar(255),
  custom_type_2      varchar(255),
  category           varchar(255),
  color              varchar(255),
  custom_label_0     varchar(255),
  custom_label_1     varchar(255),
  custom_label_2     varchar(255),
  custom_label_3     varchar(255),
  custom_label_4     varchar(255),
  description        varchar(255),
  doors              varchar(255),
  drivetrain         varchar(255),
  fuel_type          varchar(255),
  image_type         varchar(255),
  image_url          varchar(255),
  mileage            varchar(255),
  motorhome_class    varchar(255),
  pull_date_time     timestamp(6) with time zone,
  rv_category        varchar(255),
  rv_class           varchar(255),
  rv_type            varchar(255),
  transmission       varchar(255),
  trim               varchar(255),
  type               varchar(255),
  update_date        date,
  url                varchar(255),
  vehicle_type       varchar(255),
  custom_condition   varchar(255),
  custom_model       varchar(255),
  custom_trim        varchar(255)
);

CREATE INDEX IF NOT EXISTS idx_soldoutvins_customer_id
  ON public.soldoutvins (customer_id);

CREATE INDEX IF NOT EXISTS idx_soldoutvins_vin
  ON public.soldoutvins (vin);

CREATE INDEX IF NOT EXISTS idx_soldoutvins_sold_date
  ON public.soldoutvins (sold_date);

CREATE INDEX IF NOT EXISTS idx_soldoutvins_pull_date
  ON public.soldoutvins (pull_date);

COMMENT ON TABLE public.soldoutvins IS 'Sold-out VIN rows; column layout matches legacy MySQL soldoutvins-style export.';

GRANT SELECT ON public.soldoutvins TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.soldoutvins TO service_role;
