CREATE TABLE IF NOT EXISTS public.login_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  login_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email text,
  ip_address text,
  city text,
  region text,
  country text,
  timezone text,
  isp text,
  is_vpn boolean,
  is_proxy boolean,
  is_tor boolean,
  user_agent text,
  platform text,
  browser_language text,
  login_source text NOT NULL DEFAULT 'web'
);

CREATE INDEX IF NOT EXISTS login_history_user_id_login_at_idx
ON public.login_history (user_id, login_at DESC);

CREATE INDEX IF NOT EXISTS login_history_login_at_idx
ON public.login_history (login_at DESC);

ALTER TABLE public.login_history ENABLE ROW LEVEL SECURITY;

-- Users can insert only their own login event rows.
DROP POLICY IF EXISTS login_history_insert_own ON public.login_history;
CREATE POLICY login_history_insert_own
ON public.login_history
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

-- Users can see only their own rows by default.
DROP POLICY IF EXISTS login_history_select_own ON public.login_history;
CREATE POLICY login_history_select_own
ON public.login_history
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

GRANT SELECT, INSERT ON public.login_history TO authenticated;
GRANT SELECT, INSERT ON public.login_history TO service_role;
