-- ============================================================
-- Daily sales processing: log table, run function, and trigger
-- that calls the Edge Function with ?action=process via pg_net.
-- Without the trigger calling the process URL, Postman only
-- "triggers" and the actual processing never runs.
-- ============================================================

-- Enable pg_net so Postgres can call the Edge Function (enable in Dashboard if this fails)
-- Enable in Dashboard → Database → Extensions if not already: pg_net
CREATE EXTENSION IF NOT EXISTS pg_net;

-- Log table for each run (create if not already in DB)
CREATE TABLE IF NOT EXISTS public.sales_processing_log (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_date        date NOT NULL,
  customer_id     integer,
  customer_name   text,
  status          text NOT NULL,  -- 'running' | 'success' | 'error'
  notes           text,
  started_at      timestamptz NOT NULL DEFAULT clock_timestamp(),
  ended_at        timestamptz,
  elapsed_seconds numeric(10,2),
  rows_inserted   integer,
  error_message   text
);

COMMENT ON TABLE public.sales_processing_log IS 'Log for daily sales processing runs (Edge Function run_daily_sales_processing).';

-- View for "latest run" (drop first so column order can change if view already existed)
DROP VIEW IF EXISTS public.v_sales_processing_latest;
CREATE VIEW public.v_sales_processing_latest AS
  SELECT * FROM public.sales_processing_log
  WHERE run_date = (SELECT MAX(run_date) FROM public.sales_processing_log)
  ORDER BY id;

-- ============================================================
-- Runs the full daily sales processing: TRUNCATE, then
-- process_dealer_sales for each active client. Called by the
-- Edge Function when invoked with ?action=process.
-- ============================================================
CREATE OR REPLACE FUNCTION public.run_daily_sales_processing()
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_client          RECORD;
  v_inserted        integer;
  v_start           timestamptz;
  v_elapsed         numeric(10,2);
  v_run_date        date    := CURRENT_DATE;
  v_truncate_log_id bigint;
  v_dealer_log_id   bigint;
  v_error_msg       text;
BEGIN
  PERFORM pg_catalog.set_config('statement_timeout', '0', true);
  PERFORM pg_catalog.set_config('lock_timeout', '0', true);

  INSERT INTO sales_processing_log (run_date, customer_id, customer_name, status, notes)
  VALUES (v_run_date, NULL, 'SYSTEM', 'running', 'Starting daily sales processing')
  RETURNING id INTO v_truncate_log_id;

  TRUNCATE TABLE saleprocessedvins;

  UPDATE sales_processing_log
  SET    status = 'success', ended_at = now(),
         elapsed_seconds = EXTRACT(EPOCH FROM (now() - started_at)),
         notes = 'Truncate complete'
  WHERE  id = v_truncate_log_id;

  FOR v_client IN
    SELECT c.id::integer AS id, c.full_name
    FROM   clients c
    WHERE  c.is_active = TRUE
    ORDER  BY c.id
  LOOP
    v_start     := clock_timestamp();
    v_error_msg := NULL;

    INSERT INTO sales_processing_log (run_date, customer_id, customer_name, status)
    VALUES (v_run_date, v_client.id, v_client.full_name, 'running')
    RETURNING id INTO v_dealer_log_id;

    BEGIN
      v_inserted := process_dealer_sales(v_client.id, v_run_date);
      v_elapsed  := EXTRACT(EPOCH FROM (clock_timestamp() - v_start));

      UPDATE sales_processing_log
      SET    status = 'success', ended_at = clock_timestamp(),
             rows_inserted = v_inserted, elapsed_seconds = v_elapsed
      WHERE  id = v_dealer_log_id;

    EXCEPTION WHEN OTHERS THEN
      v_elapsed   := EXTRACT(EPOCH FROM (clock_timestamp() - v_start));
      v_error_msg := SQLERRM;

      UPDATE sales_processing_log
      SET    status = 'error', ended_at = clock_timestamp(),
             rows_inserted = 0, elapsed_seconds = v_elapsed,
             error_message = v_error_msg
      WHERE  id = v_dealer_log_id;
    END;

  END LOOP;
END;
$$;

-- ============================================================
-- Trigger: fire async HTTP POST to the Edge Function with
-- ?action=process. Does NOT wait for response; processing runs in background.
-- ============================================================
CREATE OR REPLACE FUNCTION public.trigger_daily_sales_processing(
  p_supabase_url text,
  p_service_key  text
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request_id bigint;
BEGIN
  -- Fire async HTTP POST to the edge function — does NOT wait for response
  SELECT net.http_post(
    url     := rtrim(p_supabase_url, '/') || '/functions/v1/daily-sales-processor-dealer-wise?action=process',
    headers := json_build_object(
                 'Content-Type',  'application/json',
                 'Authorization', 'Bearer ' || p_service_key
               )::jsonb,
    body    := '{}'::jsonb,
    timeout_milliseconds := 600000   -- process can take minutes; avoid default 2s timeout
  ) INTO v_request_id;

  RETURN json_build_object(
    'status',      'triggered',
    'request_id',  v_request_id,
    'message',     'Processing started in background. Check sales_processing_log for progress.'
  )::jsonb;
END;
$$;

-- Allow Edge Function (service_role) to call these
GRANT EXECUTE ON FUNCTION public.run_daily_sales_processing() TO anon;
GRANT EXECUTE ON FUNCTION public.run_daily_sales_processing() TO service_role;

GRANT EXECUTE ON FUNCTION public.trigger_daily_sales_processing(text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.trigger_daily_sales_processing(text, text) TO service_role;
