-- ============================================================
-- Job queue for daily sales processing: enqueue 100+ dealers,
-- process in batches via cron to avoid long transactions and timeouts.
-- ============================================================

-- Queue table: one row per dealer per run_date
CREATE TABLE IF NOT EXISTS public.sales_processing_queue (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_date        date NOT NULL,
  customer_id     integer NOT NULL,
  customer_name   text,
  status         text NOT NULL DEFAULT 'pending',  -- pending | running | success | error
  created_at      timestamptz NOT NULL DEFAULT clock_timestamp(),
  started_at      timestamptz,
  completed_at    timestamptz,
  rows_inserted   integer,
  error_message   text,
  UNIQUE (run_date, customer_id)
);

COMMENT ON TABLE public.sales_processing_queue IS 'Queue for daily sales processing; process_sales_processing_queue() works through pending rows in batches.';

CREATE INDEX IF NOT EXISTS idx_sales_processing_queue_pending
  ON public.sales_processing_queue (run_date, status)
  WHERE status = 'pending';

-- ============================================================
-- Enqueue: truncate saleprocessedvins and insert one job per
-- active client for today. Call once per day (e.g. 2am cron).
-- ============================================================
CREATE OR REPLACE FUNCTION public.enqueue_daily_sales_processing()
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_run_date  date := CURRENT_DATE;
  v_count     integer;
BEGIN
  PERFORM pg_catalog.set_config('statement_timeout', '60000', true);

  -- Clear today's queue so we can re-enqueue (idempotent for same day)
  DELETE FROM sales_processing_queue WHERE run_date = v_run_date;

  TRUNCATE TABLE saleprocessedvins;

  INSERT INTO sales_processing_queue (run_date, customer_id, customer_name, status)
  SELECT v_run_date, c.id::integer, c.full_name, 'pending'
  FROM   clients c
  WHERE  c.is_active = TRUE
  ORDER  BY c.id;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

-- ============================================================
-- Process up to p_batch_size pending jobs for today. Call from cron;
-- use batch 1 (one dealer per run) when each dealer has huge data.
-- Returns number of jobs processed.
-- ============================================================
CREATE OR REPLACE FUNCTION public.process_sales_processing_queue(p_batch_size integer DEFAULT 15)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_job      RECORD;
  v_run_date date;
  v_inserted integer;
  v_processed integer := 0;
  v_error_msg text;
BEGIN
  PERFORM pg_catalog.set_config('statement_timeout', '300000', true);

  -- Use oldest run_date that has pending jobs (avoids timezone vs CURRENT_DATE mismatch with cron)
  SELECT MIN(run_date) INTO v_run_date
  FROM   sales_processing_queue
  WHERE  status = 'pending';
  IF v_run_date IS NULL THEN
    RETURN 0;
  END IF;

  FOR v_job IN
    SELECT id, customer_id, customer_name
    FROM   sales_processing_queue
    WHERE  run_date = v_run_date
      AND  status  = 'pending'
    ORDER  BY customer_id
    LIMIT  p_batch_size
    FOR UPDATE SKIP LOCKED
  LOOP
    UPDATE sales_processing_queue
    SET    status = 'running', started_at = clock_timestamp()
    WHERE  id = v_job.id;

    BEGIN
      v_inserted := process_dealer_sales(v_job.customer_id, v_run_date);
      UPDATE sales_processing_queue
      SET    status = 'success', completed_at = clock_timestamp(),
             rows_inserted = v_inserted
      WHERE  id = v_job.id;
      v_processed := v_processed + 1;
    EXCEPTION WHEN OTHERS THEN
      v_error_msg := SQLERRM;
      UPDATE sales_processing_queue
      SET    status = 'error', completed_at = clock_timestamp(),
             rows_inserted = 0, error_message = v_error_msg
      WHERE  id = v_job.id;
      v_processed := v_processed + 1;
    END;
  END LOOP;

  RETURN v_processed;
END;
$$;

-- Optional: log to sales_processing_log for each completed queue job (keeps existing dashboard)
-- You can add a trigger or call from the app. For now we just use the queue table for status.

GRANT SELECT, INSERT, UPDATE, DELETE ON public.sales_processing_queue TO service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_daily_sales_processing() TO service_role;
GRANT EXECUTE ON FUNCTION public.process_sales_processing_queue(integer) TO service_role;

-- Cron often runs as postgres; ensure it can use the queue and functions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sales_processing_queue TO postgres;
GRANT EXECUTE ON FUNCTION public.enqueue_daily_sales_processing() TO postgres;
GRANT EXECUTE ON FUNCTION public.process_sales_processing_queue(integer) TO postgres;

-- ============================================================
-- Cron: use queue instead of one big run
-- ============================================================
-- Remove old single-job cron so we don't run both (ignore error if job not found)
DO $$
BEGIN
  PERFORM cron.unschedule('daily-sales-processing');
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- Enqueue all active dealers at 02:00 daily:
SELECT cron.schedule(
  'daily-sales-enqueue',
  '0 2 * * *',
  $$SELECT public.enqueue_daily_sales_processing()$$
);

-- Process one dealer per run (each dealer can have huge data). Every 2 min = 100 dealers in ~3.3 hours.
SELECT cron.schedule(
  'daily-sales-process-queue',
  '*/2 * * * *',
  $$SELECT public.process_sales_processing_queue(1)$$
);
